branches:
  only:
  - master

# https://github.com/travis-ci/travis-ci/issues/10055
sudo: false
language: java
#notifications:
#  email:
#    - bryncooke@gmail.com
jdk:
  # current LTS versions
  - openjdk8
  - oraclejdk8

# cache local Maven repo: https://docs.travis-ci.com/user/caching/
cache:
  directories:
  - $HOME/.m2/repository
#  - $HOME/.m2/wrapper
before_cache:
  - rm -rf $HOME/.m2/repository/org/jglue/cdi-unit/

env:
# We don't want to overtax travis (or get throttled), so we try to limit the number of combinations.
# Current strategy is, for each supported minor version of Weld, to test one early point release plus
# the most recent point release, plus some point releases which caused problems.
  - WELD_VERSION=3.0.4.Final
  - WELD_VERSION=3.0.0.Final
  - WELD_VERSION=2.4.4.Final
  # BeansXmlImpl was changed in 2.4.2
  - WELD_VERSION=2.4.2.Final
  - WELD_VERSION=2.4.0.Final
  - WELD_VERSION=2.3.5.Final
  - WELD_VERSION=2.3.0.Final
  - WELD_VERSION=2.2.13.Final
  #  2.2.7, 2.2.8 not supported, but 2.2.9 is
  - WELD_VERSION=2.2.9.Final
  - WELD_VERSION=2.2.0.Final
  - WELD_VERSION=2.1.2.Final
  - WELD_VERSION=2.1.0.Final
  - WELD_VERSION=2.0.4.Final
  - WELD_VERSION=2.0.1.Final
  - WELD_VERSION=1.1.16.Final
  - WELD_VERSION=1.1.14.Final

matrix:
  # we also test JDK 9+ on the latest version of Weld
  # note that the first WELD_VERSION above will be used by default
  include:
  # already EOL
  - jdk: openjdk9
  # feature release
  - jdk: openjdk10
  # upcoming LTS
  - jdk: openjdk11
  # early access
  - jdk: openjdk-ea
  # already EOL
#  - jdk: oraclejdk9
  # feature release
  - jdk: oraclejdk10
  # upcoming LTS
  - jdk: oraclejdk11
  # early access
#  - jdk: oraclejdk-ea

# http://docs.travis-ci.com/user/languages/java/#Dependency-Management
# http://docs.travis-ci.com/user/build-timeouts/#Build-times-out-because-no-output-was-received
# Installing the dependencies here saves many log lines (Travis limit is 10000)
install:
- |
  cp .travis.settings.xml $HOME/.m2/settings.xml
  travis_wait ./mvnw clean verify -Dmaven.main.skip -Dmaven.test.skip --quiet --batch-mode

script:
- |
  set -e
  if [[ $WELD_VERSION == 1.* || $WELD_VERSION == 2.* ]]
    then TEST_OPTS=-Dweld.test.1or2
    else TEST_OPTS=
  fi
  ./mvnw clean install --batch-mode -Dweld.test.version=${WELD_VERSION} ${TEST_OPTS}
